name: Test commits and pull requests

on:
  push:
    branches:
      - main
      - "[0-9]+.[0-9]"
      - "test-me-*"
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+(rc|a|b)[0-9]+"

  pull_request:
    branches:
      - main
      - "[0-9]+.[0-9]"

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.8', '3.9', '3.10', '3.11-dev']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coverage pytest pytest-cov mypy flake8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # F401 is "unused import", which is expected in __init__.py
        flake8 . --count --max-complexity=10 --max-line-length=120 --per-file-ignores "__init__.py: F401" --statistics
        mypy -p async_itertools
    - name: Test with pytest
      run: |
        pytest --cov=async_itertools --cov-branch --cov-fail-under=100
